package gameframework.supportfunctions;

import java.awt.*;
import java.awt.image.BufferedImage;

public class GraphicsLibrary
{
    //Determines if a given 32 bit ARGB color has a degree of transparency
    public static boolean isColorTransparent(int ARGBColor)
    {
        byte alpha = (byte)((ARGBColor & 0xFF000000) >> 24);

        if (alpha == (byte)0xFF)
            return false; //pixel is fully opaque
        else
            return true;
    }

    //Paints a pixel for the point at the requested position using the given color.
    public static void drawPixel(Graphics g, Point pixelPos, Color color)
    {
        /* There is no method to draw a single pixel in the java awt library that I know of :(
         * Therefore I have to implement this by drawing a line with the same start and end point. */
        g.setColor(color);
        g.drawLine(pixelPos.x, pixelPos.y, pixelPos.x, pixelPos.y);
    }

    // This method is used to generate a completely new buffered image from an exiting one. The new
    // image is generated by scaling the original to any proportions.
    public static BufferedImage generateScaledImage(Image originalImage, int width, int height)
    {
        if (originalImage == null)
            return null;

        BufferedImage scaledImage = new BufferedImage(width, height,
                BufferedImage.TYPE_INT_ARGB);
        Graphics drawToImage = scaledImage.createGraphics();

        drawToImage.drawImage(originalImage,
                0,0, width, height, null);

        drawToImage.dispose();

        return scaledImage;
    }

    //Compute distance between two points
    public static double computePointsDistance(Point point1, Point point2)
    {
        return Math.sqrt(Math.pow(point2.x - point1.x, 2) + Math.pow(point2.y - point1.y, 2) );
    }

}
